### ISSUE TITLE
Remove DslOriginDependencyMetaData

### ISSUE THREAD

**Issue by lptr** [prezi/gradle#5] opened 2015-02-04 13:12 UTC
We couldn’t figure out how to remove `DslOriginDependencyMetaData.getSource()`, so we still have the two different project metadata classes. What shall we do about it?

**Comment by lptr** [comment] 2015-02-04 13:26
This would also allow us to remove our secondary `DefaultProjectDetaData` implementation.

**Comment by bigdaz** [comment] 2015-02-04 18:11
I think we need to implement this correctly for now, because it's being used when we attach nodes to the root of the dependency graph:
https://github.com/prezi/gradle/blob/master/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/ResolvedConfigurationDependencyGraphVisitor.java#L75

The question is how we get the `ProjectDependency` instance given a `ProjectComponentSelector`, particularly if we need to allow `project(path: 'foo', configuration: 'bar')` in the substitution, since the configuration is lost in the `ProjectComponentSelector`. Do you think we need to support these types of dependencies? (I guess so)

So maybe we need a special `ProjectComponentSelector` implementation that holds onto the backing `ProjectDependency` and can be used here? (I need to clone your codebase so I can properly navigate to see how this might work). I need to look at bit deeper into this issue.

**Comment by bigdaz** [comment] 2015-02-04 18:33
I've confirmed that this will be a problem: I think you'll see this if you replace a top-level external dependency with a project dependency. In this case we attempt to cast to a `DslOriginDependencyMetaData` and you should see a failure.

**Comment by bigdaz** [comment] 2015-02-04 19:19
For now, I think we should create a `ProjectDependency` and a `ProjectDependencyBackedProjectComponentSelector` when we are supplied with a project reference for substitution. See `DefaultProjectDependencyFactory`.

Then, `DefaultDependencyMetaData.useTarget()` can access the `ProjectDependency` in order to create a `ProjectDependencyMetaData`. We'll also need to substitute the id in the dependencyDescriptor, like we do for `ModuleComponentSelector`.

This should let us get the first PR merged, and we can work on a better solution: we need to do something better, and I think it might involve a major refactor. I might take that on as part of the merge process.

**Comment by bigdaz** [comment] 2015-02-04 19:23
btw I have minor feedback on other aspects of your changes, but I'm planning to wait until you provide a squashed/rebased PR that is easier to review. An example would be removing some of the old constructors on `ModuleVersionResolveException` and using the new ones instead.

**Comment by lptr** [comment] 2015-02-04 23:22
We were thinking about having to support something along the lines of:

``` groovy
useTarget project(path: ":some-project", configuration: "compile")
```

But then we thought that a `ModuleComponentSelector` has no way to select a configuration (and neither did a `ModuleVersionSelector`), so we couldn't switch configurations before either. And it seems alright, in a way: the configurations chosen are part of the `DependencyMetaData`'s `DependencyDescriptor`, which is carried over to the substituted dependency.

For our use-case at least, it makes sense that if we have an external dependency pointing to configuration "whatever", then you can only replace that with a project dependency (or another external dependency) that points to the same configuration.

Anyway, I can see how a `ProjectDependencyBackedProjectComponentSelector` could be useful, but in that case, I guess we'd need to update the configurations addressed in the `DependencySelector` as well.

And if we provide the option to override the dependency's configuration as well during substitution for project dependencies, then I guess we'd need to be able to do the same for external dependencies as well.

That said, this configuration override feature seems like something that should be handled as a separate feature, and it's also something we don't need for Pride. So unless we find a reason why this is essential, I'd push this to a different scope.

**Comment by lptr** [comment] 2015-02-04 23:25
About squashing some commits, we can do that today.

**Comment by lptr** [comment] 2015-02-05 13:47
Here's some more thought about using a `ProjectDependency` when replacing an external dependency.

So, the syntax would be something like this, I guess:

``` groovy
    useTarget project(path: ":some-project", configuration: "compile")
```

I guess one of the more popular cases would be to replace the dependency with the same project configuration. But `DependencyResovleDetails` does not offer a way to get to that information.

We could expose it (or even expose the whole `DependencyMetaData` thing), but even then we'd need to have a way to replace an external dep with a project, keeping all the baggage (configurations, exclusion rules etc.) with the current:

``` groovy
    useTarget project(":some-project")
```

Adding support for more complicated replacements could go into the improved DSL feature.

**Comment by bigdaz** [comment] 2015-02-05 14:00
Sorry, I guess I combined 2 different things:
1. Support for the project dependency notation: I agree that this isn't required, or perhaps even desirable in `DependencyResolveDetails`
2. Having a `ProjectDependency` under the covers, that can be used for `DslOriginDependencyMetaData.getSource()`. This is what I was suggesting we might do.

So for 2) we'd create a `ProjectDependency` from the supplied `Project` instance, and use this when creating a `ProjectDependencyMetaData`. The issue is that we then have 2 different Ivy `DependencyDescriptor` instances, and no way to merge them.

**Comment by bigdaz** [comment] 2015-02-05 14:03
There's something about GitHub comments that make it easy to close the issue when all I wanted to do is close my comment without posting....

**Comment by bigdaz** [comment] 2015-02-05 18:45
I solved this issue by making the DslOriginDependencyMetaData a delegating wrapper around DependencyMetaData, together with using the type of `getSelector()` rather than a `ProjectDependnecyMetaData` to detect a project dependency.

This allowed me to remove `ProjectDependencyMetaData` completely.

**Closed as completed by bigdaz** 2015-02-05 18:45 UTC
Labels: question
